export const quizData = [
    {
        question: 'Hangisi Yazılım Dilidir ?',
        a: 'PHYTON',
        b: 'React',
        c: 'HTML',
        d: 'CSS',
        e: 'Hepsi',
        correct: 'a',
    },
    {
        question: 'Aşağıdakilerden Hangsi JS Kütüphanesidir ?',
        a: 'React',
        b: 'TYPESCRİPT',
        c: 'ANGULAR',
        d: 'VEU',
        e: 'HEPSİ',
        correct: 'e',
    },
    {
        question: 'JavaScript çıkış yılı?',
        a: '1999',
        b: '2000',
        c: '1997',
        d: '1995',
        e: '1994',
        correct: 'd',
    },
    {
        question: 'JavaScript hangi kod blok arasına yazılır?',
        a: '<javascript>',
        b: '<js>',
        c: '<script>',
        d: '<scr>',
        e: '<scipting>',
        correct: 'c',
    },
    {
        question: 'Bilgisayarın Çıkış yılı ?',
        a: '1890',
        b: '1888',
        c: '1885',
        d: '1880',
        e: '1833',
        correct: 'e',
    },
]
